name: DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast:
    name: OWASP ZAP BASELINE SCAN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run DAST scan with Docker Compose
        run: |
          docker-compose up --abort-on-container-exit
