name: DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast:
    name: OWASP ZAP BASELINE SCAN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: Run DAST scan with Docker Compose
        run: |
          docker-compose up --abort-on-container-exit
